# Generated by Django 3.2.22 on 2023-10-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productimage_is_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
