version: '3'
services:
  ustora_db:
    image: mysql:8
    volumes:
      - 'ustora-mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ustora
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - ustora
  ustora_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=ustora
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=ustora_db
    depends_on:
      - ustora_db
    networks:
      - ustora
networks:
  ustora:
      driver: bridge
volumes:
  ustora-mysql:
      driver: local
