# Generated by Django 3.2.22 on 2023-10-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0007_alter_slider_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.ImageField(upload_to='asset/images/sliders'),
        ),
    ]
